# SonarQube Project Configuration
sonar.host.url=http://localhost:9000
sonar.token=sqp_ac5429c6a6cba939fe28ed0eecf6567342f4837c
sonar.projectKey=PTE-Exam-Prep-Platform-Backend
sonar.projectName=PTE-Exam-Prep-Platform-Backend

# Force using system Node.js instead of embedded node runtime
sonar.nodejs.executable=C:/Program Files/nodejs/node.exe

# Redirect working directory outside Desktop to bypass Controlled Folder Access block
sonar.working.directory=C:/Users/acer/AppData/Local/Temp/sonar-work-backend

# Source & Test Configurations
sonar.sources=src
sonar.exclusions=node_modules/**, **/*.test.js
sonar.tests=tests
sonar.test.inclusions=**/*.test.js

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage Reports
sonar.javascript.lcov.reportPaths=coverage/lcov.info
